spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/qipai_tasks
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: false
        bindings:
          activity:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          tasks:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
      bindings:
        members:
          destination: members
          group: qipai_tasks
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        activity:
          destination: activity
          contentType: application/json
          producer:
            partitionCount: 1
        tasks:
          destination: tasks
          contentType: application/json
          producer:
            partitionCount: 1
  application:
    name: qipai-tasks
server:
  port: 98
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/