spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/qipai_tasks

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: false
        bindings:
          activity:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          tasks:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          finishTasks:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          memberGoldsAccounting:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          memberScoresAccounting:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          memberVIPAccounting:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          memberHongbaodianAccounting:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          memberHongbaoRMBAccounting:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
      bindings:
        members:
          destination: members
          group: qipai-tasks
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        memberLoginRecord:
          destination: memberLoginRecord
          group: qipai-tasks
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        memberInvitationRecord:
          destination: memberInvitationRecord
          group: qipai-tasks
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        gameRuianmjResult:
          destination: gameRuianmjResult
          group: qipai-tasks
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        gameFangpaomjResult:
          destination: gameFangpaomjResult
          group: qipai-tasks
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        gameWenzhoumjResult:
          destination: gameWenzhoumjResult
          group: qipai-tasks
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        gameDianpaomjResult:
          destination: gameDianpaomjResult
          group: qipai-tasks
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        gameWenzhouskResult:
          destination: gameWenzhouskResult
          group: qipai-tasks
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        gameDoudizhuResult:
          destination: gameDoudizhuResult
          group: qipai-tasks
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        gameChayuanskResult:
          destination: gameChayuanskResult
          group: qipai-tasks
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        wisecrack:
          destination: wisecrack
          group: qipai-tasks
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        activity:
          destination: activity
          contentType: application/json
          producer:
            partitionCount: 1
        tasks:
          destination: tasks
          contentType: application/json
          producer:
            partitionCount: 1
        finishTasks:
          destination: finishTasks
          contentType: application/json
          producer:
            partitionCount: 1
        memberGoldsAccounting:
          destination: memberGoldsAccounting
          contentType: application/json
          producer:
            partitionCount: 1
        memberScoresAccounting:
          destination: memberScoresAccounting
          contentType: application/json
          producer:
            partitionCount: 1
        memberVIPAccounting:
          destination: memberVIPAccounting
          contentType: application/json
          producer:
            partitionCount: 1
        memberHongbaodianAccounting:
          destination: memberHongbaodianAccounting
          contentType: application/json
          producer:
            partitionCount: 1
        memberHongbaoRMBAccounting:
          destination: memberHongbaoRMBAccounting
          contentType: application/json
          producer:
            partitionCount: 1
        whitelist:
          destination: whitelist
          group: qipai-tasks
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
  application:
    name: qipai-tasks
server:
  port: 98
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  #instance:
    #prefer-ip-address: true
    #instance-id: http://172.16.21.50:98